ALTER TABLE public.chalet_bookings
  ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'LKR',
  ADD COLUMN IF NOT EXISTS service_charge_pct NUMERIC NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS vat_pct NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sscl_pct NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cancellation_reason TEXT,
  ADD COLUMN IF NOT EXISTS refund_status TEXT NOT NULL DEFAULT 'not_required'
    CHECK (refund_status IN ('not_required', 'pending', 'refunded')),
  ADD COLUMN IF NOT EXISTS refund_amount NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS refund_service_charge_retained NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS refund_notes TEXT;
